# Generated by Django 5.2.8 on 2025-12-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20251126_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='banniere_cours/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon_cours/')),
                ('type_cours', models.CharField(choices=[('Positionnement', 'Parcours de positionnement'), ('Standard', 'Cours')], default='Standard', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='users.matiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='users.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='dashboards.cours')),
            ],
        ),
    ]
