# Generated by Django 5.2.8 on 2025-12-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['ordre']},
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('cours', 'ordre'), name='unique_ordre_par_cours'),
        ),
    ]
