# Generated by Django 5.2.8 on 2025-12-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_alter_module_options_module_unique_ordre_par_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='niveau_module',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Avancé')], null=True),
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('enonce', models.TextField()),
                ('type_exercice', models.CharField(choices=[('QCM', 'Questionnaire à choix multiples'), ('CODE', 'Exercice de programmation')], max_length=10)),
                ('niveau_exercice', models.PositiveIntegerField(blank=True, choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Avancé')], null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='dashboards.module')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langage', models.CharField(choices=[('python', 'Python'), ('java', 'JAVA'), ('javascript', 'Javascript'), ('php', 'PHP'), ('html', 'HTML/CSS')], max_length=20)),
                ('code_initial', models.TextField(blank=True, help_text='Code affiché au début')),
                ('solution_attendue', models.TextField(help_text='Code de référence ou résultat attendu')),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contenu_code', to='dashboards.exercice')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboards.exercice')),
            ],
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='dashboards.questionqcm')),
            ],
        ),
    ]
