# Generated by Django 5.2.8 on 2025-11-26 09:29

from django.db import migrations

def create_initial_data(apps, schema_editor):
    AnneeScolaire = apps.get_model('users', 'AnneeScolaire')
    Option = apps.get_model('users', 'Option')

    # Créer les années scolaires
    AnneeScolaire.objects.get_or_create(nom="1ère année")
    AnneeScolaire.objects.get_or_create(nom="2ème année")

    # Créer les options
    Option.objects.get_or_create(nom="Solutions Logicielles et Application Métiers - SLAM")
    Option.objects.get_or_create(nom="Solutions d'Infrastructure, Systèmes et Réseaux - SISR")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]